language: r
cache: packages
matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: beta-xcode6.2
r_packages:
- covr
r_github_packages:
- ropensci/tabulizerjars
after_success:
- Rscript -e 'library("covr");codecov()'
#- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash knitreadme.sh
